<?php
session_start();
unset($_SESSION["id_user"]);
unset($_SESSION["nom"]);
unset($_SESSION["prenom"]);
unset($_SESSION["email"]);
unset($_SESSION["mdp"]);
unset($_SESSION["role"]);
header("Location:login.php");
?>